[wokwi]
version = 1
firmware = '.pio/build/espink/firmware.bin'
elf = '/.pio/build/espink/firmware.elf'
rfc2217ServerPort = 4000

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "target:80"

